QT       += core gui
TARGET = targettest
TEMPLATE = app
HEADERS += \
./Project/diskio.h\
./Project/ff.h\
./Project/ffconf.h\
./Project/lpc17xx_rtc.h\
./Project/lpc17xx_spi.h\
./Project/msc.h\
./Project/mscuser.h\
./Project/sd.h\
./Project/sdi.h\
./Project/spi.h\
./Project/type.h\
./Project/usb.h\
./Project/usbcfg.h\
./Project/usbcore.h\
./Project/usbdesc.h\
./Project/usbhw.h\
./Project/usbreg.h\
./Project/usbuser.h\
./inc/temp/mci.h\
./inc/core_cm3.h\
./inc/diskio.h\
./inc/integer.h\
./inc/irq.h\
./inc/lpc17xx_uart.h\
./inc/system_LPC17xx.h\
./inc/type.h\
./inc/usbhost_uart.h\
./src/10Task/initialization.h\
./src/11DisMenu/CAnnotate.h\
./src/11DisMenu/CCompInten.h\
./src/11DisMenu/CCompReg.h\
./src/11DisMenu/CCompSet.h\
./src/11DisMenu/CCompStat.h\
./src/11DisMenu/CDateMod.h\
./src/11DisMenu/CHistoryList.h\
./src/11DisMenu/CLocalSet.h\
./src/11DisMenu/CModelFault.h\
./src/11DisMenu/CSysCheck.h\
./src/11DisMenu/CSysReset.h\
./src/11DisMenu/CTestSelf.h\
./src/11DisMenu/alarmenu.h\
./src/11DisMenu/batteryLow.h\
./src/11DisMenu/breakdown.h\
./src/11DisMenu/checkmenu.h\
./src/11DisMenu/mainmenu.h\
./src/11DisMenu/setmenu.h\
./src/11DisMenu/startmenu.h\
./src/11DisMenu/testmenu.h\
./src/12UARTHandle/CAlarmBuffer.h\
./src/12UARTHandle/CComAnn.h\
./src/12UARTHandle/CComHandle.h\
./src/12UARTHandle/CComPara.h\
./src/13CirCon/CAddressCount.h\
./src/14Sand195/CSendTo195.h\
./src/20RunCtrl/CGetGrap.h\
./src/20RunCtrl/CKeyCounter.h\
./src/20RunCtrl/CTaskDown.h\
./src/20RunCtrl/CTaskReturn.h\
./src/20RunCtrl/CTaskSure.h\
./src/20RunCtrl/CTaskUp.h\
./src/20RunCtrl/runfunction.h\
./src/20RunCtrl/tasklevel.h\
./src/20RunCtrl/tasklist.h\
./src/20RunCtrl/tasklist_backup.h\
./src/APP/Config.h\
./src/APP/include.h\
./src/APP/main.h\
./src/APP/publicparam.h\
./src/Board/CLED.h\
./src/Board/CRelay.h\
./src/Board/key.h\
./src/Board/lcd.h\
./src/Board/pcf8563.h\
./src/Hardware/CSSP/ssp.h\
./src/Hardware/Extint/extint.h\
./src/Hardware/GPIO/GPIOInit.h\
./src/Hardware/I2C/i2c.h\
./src/Hardware/Timer/CTime.h\
./src/Hardware/Timer/CTimeDef.h\
./src/Hardware/Timer/timer.h\
./src/Hardware/UART/uart.h\
./src/Hardware/Delay.h\
./src/Hardware/PWM.h\
./src/Share/16by16ziku.h\
./src/Share/CFlashParam.h\
./src/Share/CGetCompSum.h\
./src/Share/CGrapParam.h\
./src/Share/CIntStEnd.h\
./src/Share/CMaDefine.h\
./src/Share/CSendToFlash.h\
./src/Share/CSetCurrent.h\
./src/Share/CSpeaker.h\
./src/Share/CTimerTask.h\
./src/Share/HZK16F.h\
./src/Share/buffer.h\
./src/Share/hzk12by12.h\
./src/Share/hzk16by16 - 3500³£ÓÃºº×Ö.h\
./src/Share/hzk16by16 - ËùÓÐºº×Ö.h\
./src/Share/hzk16by16.h\
./src/Share/ziku.h\
./m25p80.h
SOURCES += \
./Project/Retarget.c\
./Project/Serial.c\
./Project/ccsbcs.c\
./Project/ff.c\
./Project/lpc17xx_rtc.c\
./Project/lpc17xx_spi.c\
./Project/mscuser.c\
./Project/sd.c\
./Project/sd1.c\
./Project/usbcore.c\
./Project/usbdesc.c\
./Project/usbhw.c\
./Project/usbuser.c\
./inc/temp/mci.c\
./src/10Task/initialization.c\
./src/11DisMenu/CAnnotate.c\
./src/11DisMenu/CCompInten.c\
./src/11DisMenu/CCompReg.c\
./src/11DisMenu/CCompSet.c\
./src/11DisMenu/CCompStat.c\
./src/11DisMenu/CDateMod.c\
./src/11DisMenu/CHistoryList.c\
./src/11DisMenu/CLocalSet.c\
./src/11DisMenu/CModelFault.c\
./src/11DisMenu/CSysCheck.c\
./src/11DisMenu/CSysReset.c\
./src/11DisMenu/CTestSelf.c\
./src/11DisMenu/alarmenu.c\
./src/11DisMenu/batteryLow.c\
./src/11DisMenu/breakdown.c\
./src/11DisMenu/checkmenu.c\
./src/11DisMenu/mainmenu.c\
./src/11DisMenu/setmenu.c\
./src/11DisMenu/startmenu.c\
./src/11DisMenu/testmenu.c\
./src/12UARTHandle/CAlarmBuffer.c\
./src/12UARTHandle/CComAnn.c\
./src/12UARTHandle/CComHandle.c\
./src/12UARTHandle/CComPara.c\
./src/13CirCon/CAddressCount.c\
./src/14Sand195/CSendTo195.c\
./src/20RunCtrl/CGetGrap.c\
./src/20RunCtrl/CKeyCounter.c\
./src/20RunCtrl/CTaskDown.c\
./src/20RunCtrl/CTaskReturn.c\
./src/20RunCtrl/CTaskSure.c\
./src/20RunCtrl/CTaskUp.c\
./src/20RunCtrl/runfunction.c\
./src/20RunCtrl/tasklevel.c\
./src/20RunCtrl/tasklist.c\
./src/20RunCtrl/tasklist_backup.c\
./src/APP/main.c\
./src/Board/CLED.c\
./src/Board/CRelay.c\
./src/Board/key.c\
./src/Board/lcd.c\
./src/Board/pcf8563.c\
./src/Hardware/CSSP/ssp.c\
./src/Hardware/Extint/extint.c\
./src/Hardware/I2C/i2c.c\
./src/Hardware/Timer/CTime.c\
./src/Hardware/Timer/CTimeDef.c\
./src/Hardware/Timer/timer.c\
./src/Hardware/UART/uart.c\
./src/Hardware/Delay.c\
./src/Hardware/PWM.c\
./src/Share/CFlashParam.c\
./src/Share/CGetCompSum.c\
./src/Share/CGrapParam.c\
./src/Share/CIntStEnd.c\
./src/Share/CSendToFlash.c\
./src/Share/CSetCurrent.c\
./src/Share/CSpeaker.c\
./src/Share/CTimerTask.c\
./src/Share/buffer.c\
./src/core_cm3.c\
./src/system_LPC17xx.c\
./src/target.c\
./src/timer.c\
./m25p80.c
OTHER_FILES += \
./Project/output/139W.axf\
./Project/output/139W.bin\
./Project/output/139W.hex\
./Project/output/139W.htm\
./Project/output/139W.lnp\
./Project/output/139W.plg\
./Project/output/139W.sct\
./Project/output/139W.tra\
./Project/output/ExtDll.iex\
./Project/output/alarmenu.crf\
./Project/output/alarmenu.d\
./Project/output/alarmenu.o\
./Project/output/batterylow.crf\
./Project/output/batterylow.d\
./Project/output/batterylow.o\
./Project/output/breakdown.crf\
./Project/output/breakdown.d\
./Project/output/breakdown.o\
./Project/output/buffer.crf\
./Project/output/buffer.d\
./Project/output/buffer.o\
./Project/output/caddresscount.crf\
./Project/output/caddresscount.d\
./Project/output/caddresscount.o\
./Project/output/cannotate.crf\
./Project/output/cannotate.d\
./Project/output/cannotate.o\
./Project/output/ccomann.crf\
./Project/output/ccomann.d\
./Project/output/ccomann.o\
./Project/output/ccomhandle.crf\
./Project/output/ccomhandle.d\
./Project/output/ccomhandle.o\
./Project/output/ccompara.crf\
./Project/output/ccompara.d\
./Project/output/ccompara.o\
./Project/output/ccompinten.crf\
./Project/output/ccompinten.d\
./Project/output/ccompinten.o\
./Project/output/ccompreg.crf\
./Project/output/ccompreg.d\
./Project/output/ccompreg.o\
./Project/output/ccompset.crf\
./Project/output/ccompset.d\
./Project/output/ccompset.o\
./Project/output/ccompstat.crf\
./Project/output/ccompstat.d\
./Project/output/ccompstat.o\
./Project/output/cdatemod.crf\
./Project/output/cdatemod.d\
./Project/output/cdatemod.o\
./Project/output/cflashparam.crf\
./Project/output/cflashparam.d\
./Project/output/cflashparam.o\
./Project/output/cgetcompsum.crf\
./Project/output/cgetcompsum.d\
./Project/output/cgetcompsum.o\
./Project/output/cgetgrap.crf\
./Project/output/cgetgrap.d\
./Project/output/cgetgrap.o\
./Project/output/cgrapparam.crf\
./Project/output/cgrapparam.d\
./Project/output/cgrapparam.o\
./Project/output/checkmenu.crf\
./Project/output/checkmenu.d\
./Project/output/checkmenu.o\
./Project/output/chistorylist.crf\
./Project/output/chistorylist.d\
./Project/output/chistorylist.o\
./Project/output/cintstend.crf\
./Project/output/cintstend.d\
./Project/output/cintstend.o\
./Project/output/ckeycounter.crf\
./Project/output/ckeycounter.d\
./Project/output/ckeycounter.o\
./Project/output/cled.crf\
./Project/output/cled.d\
./Project/output/cled.o\
./Project/output/clocalset.crf\
./Project/output/clocalset.d\
./Project/output/clocalset.o\
./Project/output/cmodelfault.crf\
./Project/output/cmodelfault.d\
./Project/output/cmodelfault.o\
./Project/output/core_cm3.crf\
./Project/output/core_cm3.d\
./Project/output/core_cm3.o\
./Project/output/crelay.crf\
./Project/output/crelay.d\
./Project/output/crelay.o\
./Project/output/csendto195.crf\
./Project/output/csendto195.d\
./Project/output/csendto195.o\
./Project/output/csendtoflash.crf\
./Project/output/csendtoflash.d\
./Project/output/csendtoflash.o\
./Project/output/csetcurrent.crf\
./Project/output/csetcurrent.d\
./Project/output/csetcurrent.o\
./Project/output/cspeaker.crf\
./Project/output/cspeaker.d\
./Project/output/cspeaker.o\
./Project/output/csyscheck.crf\
./Project/output/csyscheck.d\
./Project/output/csyscheck.o\
./Project/output/csysreset.crf\
./Project/output/csysreset.d\
./Project/output/csysreset.o\
./Project/output/ctaskdown.crf\
./Project/output/ctaskdown.d\
./Project/output/ctaskdown.o\
./Project/output/ctaskreturn.crf\
./Project/output/ctaskreturn.d\
./Project/output/ctaskreturn.o\
./Project/output/ctasksure.crf\
./Project/output/ctasksure.d\
./Project/output/ctasksure.o\
./Project/output/ctaskup.crf\
./Project/output/ctaskup.d\
./Project/output/ctaskup.o\
./Project/output/ctestself.crf\
./Project/output/ctestself.d\
./Project/output/ctestself.o\
./Project/output/ctime.crf\
./Project/output/ctime.d\
./Project/output/ctime.o\
./Project/output/ctimedef.crf\
./Project/output/ctimedef.d\
./Project/output/ctimedef.o\
./Project/output/ctimertask.crf\
./Project/output/ctimertask.d\
./Project/output/ctimertask.o\
./Project/output/delay.crf\
./Project/output/delay.d\
./Project/output/delay.o\
./Project/output/extint.crf\
./Project/output/extint.d\
./Project/output/extint.o\
./Project/output/gpioinit.crf\
./Project/output/gpioinit.d\
./Project/output/gpioinit.o\
./Project/output/i2c.crf\
./Project/output/i2c.d\
./Project/output/i2c.o\
./Project/output/initialization.crf\
./Project/output/initialization.d\
./Project/output/initialization.o\
./Project/output/key.crf\
./Project/output/key.d\
./Project/output/key.o\
./Project/output/lcd.crf\
./Project/output/lcd.d\
./Project/output/lcd.o\
./Project/output/main.crf\
./Project/output/main.d\
./Project/output/main.o\
./Project/output/mainmenu.crf\
./Project/output/mainmenu.d\
./Project/output/mainmenu.o\
./Project/output/pcf8563.crf\
./Project/output/pcf8563.d\
./Project/output/pcf8563.o\
./Project/output/pwm.crf\
./Project/output/pwm.d\
./Project/output/pwm.o\
./Project/output/runfunction.crf\
./Project/output/runfunction.d\
./Project/output/runfunction.o\
./Project/output/setmenu.crf\
./Project/output/setmenu.d\
./Project/output/setmenu.o\
./Project/output/ssp.crf\
./Project/output/ssp.d\
./Project/output/ssp.o\
./Project/output/startmenu.crf\
./Project/output/startmenu.d\
./Project/output/startmenu.o\
./Project/output/startup_LPC17xx.d\
./Project/output/startup_LPC17xx.o\
./Project/output/system_lpc17xx.crf\
./Project/output/system_lpc17xx.d\
./Project/output/system_lpc17xx.o\
./Project/output/tasklist.crf\
./Project/output/tasklist.d\
./Project/output/tasklist.o\
./Project/output/testmenu.crf\
./Project/output/testmenu.d\
./Project/output/testmenu.o\
./Project/output/uart.crf\
./Project/output/uart.d\
./Project/output/uart.o\
./Project/JLinkArm_usb_disk_test.ini\
./Project/JLinkLog.txt\
./Project/JLinkSettings.ini\
./Project/QQ½ØÍ¼Î´ÃüÃû.jpg\
./Project/usb_disk_test.lnp\
./Project/usb_disk_test.plg\
./Project/usb_disk_test.sct\
./Project/usb_disk_test.uvgui.Administrator\
./Project/usb_disk_test.uvgui.grant\
./Project/usb_disk_test.uvgui.lenovo\
./Project/usb_disk_test.uvgui.xiaoweilai\
./Project/usb_disk_test.uvgui_Administrator.bak\
./Project/usb_disk_test.uvgui_lenovo.bak\
./Project/usb_disk_test.uvgui_xiaoweilai.bak\
./Project/usb_disk_test.uvopt\
./Project/usb_disk_test.uvproj\
./Project/usb_disk_test_usb_disk_test.dep\
./Project/usb_disk_test_uvopt.bak\
./Project/usb_disk_test_uvproj.bak\
./inc/temp/mci.crf\
./inc/temp/mci.d\
./inc/temp/mci.o\
./inc/LPC17xx.H\
./list/139W.map\
./list/alarmenu.i\
./list/batterylow.i\
./list/breakdown.i\
./list/buffer.i\
./list/caddresscount.i\
./list/cannotate.i\
./list/ccomann.i\
./list/ccomhandle.i\
./list/ccompara.i\
./list/ccompinten.i\
./list/ccompreg.i\
./list/ccompset.i\
./list/ccompstat.i\
./list/cdatemod.i\
./list/cflashparam.i\
./list/cgetcompsum.i\
./list/cgetgrap.i\
./list/cgrapparam.i\
./list/checkmenu.i\
./list/chistorylist.i\
./list/cintstend.i\
./list/ckeycounter.i\
./list/cled.i\
./list/clocalset.i\
./list/cmodelfault.i\
./list/core_cm3.i\
./list/crelay.i\
./list/csendto195.i\
./list/csendtoflash.i\
./list/csetcurrent.i\
./list/cspeaker.i\
./list/csyscheck.i\
./list/csysreset.i\
./list/ctaskdown.i\
./list/ctaskreturn.i\
./list/ctasksure.i\
./list/ctaskup.i\
./list/ctestself.i\
./list/ctime.i\
./list/ctimedef.i\
./list/ctimertask.i\
./list/delay.i\
./list/extint.i\
./list/gpioinit.i\
./list/i2c.i\
./list/initialization.i\
./list/key.i\
./list/lcd.i\
./list/main.i\
./list/mainmenu.i\
./list/pcf8563.i\
./list/pwm.i\
./list/runfunction.i\
./list/setmenu.i\
./list/ssp.i\
./list/startmenu.i\
./list/startup_LPC17xx.lst\
./list/system_lpc17xx.i\
./list/tasklist.i\
./list/testmenu.i\
./list/uart.i\
./list/usb_disk_test.map\
./src/Hardware/GPIO/GPIOInit.C\
./src/startup_LPC17xx.s\
./LPC1768_V1_3.pro\
./findcandcpptolist.R.exe


INCLUDEPATH +=\
./Project\
./Project/output\
./inc\
./inc/temp\
./list\
./src\
./src/10Task\
./src/11DisMenu\
./src/12UARTHandle\
./src/13CirCon\
./src/14Sand195\
./src/20RunCtrl\
./src/APP\
./src/Board\
./src/Hardware\
./src/Hardware/CSSP\
./src/Hardware/Extint\
./src/Hardware/GPIO\
./src/Hardware/I2C\
./src/Hardware/Timer\
./src/Hardware/UART\
./src/Share
